export {default as generateTile} from './generateTile'
export {default as move} from './move'
export {default as getMoveDirection} from './getMoveDirection'
export {default as startGame} from './startGame'
export {default as blankTiles} from './blankTiles'
