export { default as generateTile } from './generateTile'
export { default as move } from './move'
export { default as getKeyboardMoveDirection } from './getKeyboardMoveDirection'
export { default as startGame } from './startGame'
export { default as blankTiles } from './blankTiles'
export { default as sortTiles } from './sortTiles'
export { default as checkGameOver } from './checkGameOver'
export { default as onUse } from './onUse'
